### ISSUE TITLE
Validation Error: Tool has an output schema but did not return structured content

### ISSUE THREAD

**Issue by rahadiankr** [rekog-labs/MCP-Nest#79]
I’ve been testing my tool in MCP Inspector and it successfully fetches the correct data. However, I’m still encountering the following error when the agent tries to call it:

`McpError: MCP error -32600: Tool getUserProfile has an output schema but did not return structured content`
In the Inspector, I can see the returned object. But MCP rejects it, stating that the output does not match the declared schema—even though I haven’t defined an explicit schema, and MCP inspector shows:
```

{
  "type": "object",
  "$schema": "http://json‑schema.org/draft‑07/schema#"
}

```

I’m not sure how MCP interprets this as having a schema, nor what the correct structure should be. Here’s a snapshot of the returned data:

`{ "profile": { "avatar": …, "name": …, "level": …, … } }`

What I’d like to know:
How can I correctly declare or remove the output schema so that MCP accepts this structured return?
Is there a recommended schema format or decorator adjustment to make this work?
Thanks in advance for any guidance!

and here is my tool
```

@Tool({
        name: 'getUserProfile',
        description: 'return the user profile data',
        parameters: z.object({
            userId: z.string().describe('The ID of the user to get the profile for'),
        }),
    })
    async getFullProfileById(userId: string, context: Context,) {
        const totalSteps = 1;
        if (typeof userId === 'object' && userId !== null && 'userId' in userId) {
            userId = (userId as { userId: string }).userId || userId;
        }
        const user = await this.prisma.user.findUnique({
            where: { id: userId },
        });
        if (!user) {
            throw new NotFoundException(`User with id '${userId}' not found`);
        }
        for (let i = 0; i < totalSteps; i++) {
            await new Promise((resolve) => setTimeout(resolve, 100));
            // Send a progress update.
            await context.reportProgress({
                progress: (i + 1) * 20,
                total: 100,
            } as Progress);
        }
        const data = await this.profileService.getProfile(user);

        return {
            content: [
                {
                    type: 'text',
                    text: JSON.stringify(data),
                }
            ]
        }
    }

```

![Image](https://github.com/user-attachments/assets/d25892dc-843f-4f44-8fc5-fa5dffdab92a)

**Comment by november11th** [comment]
This issue was resolved in commit #77.

The released version now needs to be published to the npm repository.

**Comment by rahadiankr** [comment]
awesome Thankyou!

**Comment by rahadiankr** [comment]
> This issue was resolved in commit [#77](https://github.com/rekog-labs/MCP-Nest/pull/77).
> 
> The released version now needs to be published to the npm repository.

The latest version is 1.6.1 — I have already updated to it, but the error still persists.

**Comment by rinormaloku** [comment]
I just released a new version 1.6.2, can you give it a try

**Comment by rahadiankr** [comment]
Thank you for the quick release! I’ve upgraded to version 1.6.2, and I can confirm that the issue is now resolved and working correctly. ✅ Everything is functioning as expected on my end.

Much appreciated! 🙏

**Comment by rinormaloku** [comment]
Thanks @november11th for contributing the fix!
